DROP TABLE NEW_DONEE;

CREATE TABLE NEW_DONEE
(
	ID NUMBER,
	NAME VARCHAR2(50),
	MOBILE VARCHAR2(12),
	BLOOD_GROUP VARCHAR2(4),
	LOCATION VARCHAR2(20),
	COMPLICATIONS VARCHAR2(50),
	QUANTITY NUMBER,
	APPROX_DATE DATE,
	EM_PERSON VARCHAR2(50),
	EM_MOBILE VARCHAR2(12),
	CONSTRAINT NEW_DONEE_PK PRIMARY KEY (ID)
);

DROP SEQUENCE DONEE_SEQUENCE;
CREATE SEQUENCE DONEE_SEQUENCE;

CREATE OR REPLACE TRIGGER NEW_DONEE_ON_INSERT
BEFORE INSERT ON NEW_DONEE
FOR EACH ROW
BEGIN
SELECT DONEE_SEQUENCE.NEXTVAL
INTO :NEW.ID
FROM DUAL;
END;
/


CREATE TABLE LOCATIONS
(
	NAME VARCHAR2(20) PRIMARY KEY
);

INSERT INTO LOCATIONS VALUES ('MIRPUR');
INSERT INTO LOCATIONS VALUES ('UTTARA');
INSERT INTO LOCATIONS VALUES ('BANANI');
INSERT INTO LOCATIONS VALUES ('GULSHAN');
INSERT INTO LOCATIONS VALUES ('DHANMONDI');
INSERT INTO LOCATIONS VALUES ('BARIDHARA');
INSERT INTO LOCATIONS VALUES ('MOGBAZAR');
INSERT INTO LOCATIONS VALUES ('KAMLAPUR');
INSERT INTO LOCATIONS VALUES ('MOTIJHEEL');
INSERT INTO LOCATIONS VALUES ('FARMGATE');
INSERT INTO LOCATIONS VALUES ('SHAHABAG');
INSERT INTO LOCATIONS VALUES ('NEW MARKET');
INSERT INTO LOCATIONS VALUES ('AZIMPUR');
INSERT INTO LOCATIONS VALUES ('MOHAMMADPUR');
INSERT INTO LOCATIONS VALUES ('GULISTAN');
INSERT INTO LOCATIONS VALUES ('JATRABARI');

CREATE TABLE REGISTRATION
(
    USERNAME VARCHAR2(20) PRIMARY KEY,
    PASSWORD VARCHAR2(20),
    USER_TYPE VARCHAR2(15)
);

CREATE TABLE PERSONAL_INFO
(
    USERNAME VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(50),
    MOBILE VARCHAR2(12),
    EMAIL VARCHAR2(50),
    DOB DATE,
    LOCATION VARCHAR2(15),
    GENDER VARCHAR2(10),
    BLOOD_GROUP VARCHAR2(4)
);

CREATE TABLE ORG_INFO
(
    USERNAME VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(100),
    CONTACT VARCHAR2(12),
    EMAIL VARCHAR2(50),
    LOCATION VARCHAR2(15),
    LIC_NO VARCHAR2(50),
    CONTACT_PERSON VARCHAR2(50),
    CP_MOBILE VARCHAR2(12),
    DESCRIPTION VARCHAR2(250)
);

/*
SELECT * FROM REGISTRATION;
SELECT * FROM PERSONAL_INFO;
SELECT * FROM ORG_INFO;
*/