DROP TABLE NEW_DONEE;

CREATE TABLE NEW_DONEE
(
	ID NUMBER,
	NAME VARCHAR2(50),
	MOBILE VARCHAR2(12),
	BLOOD_GROUP VARCHAR2(4),
	LOCATION VARCHAR2(20),
	COMPLICATIONS VARCHAR2(50),
	QUANTITY NUMBER,
	APPROX_DATE DATE,
	EM_PERSON VARCHAR2(50),
	EM_MOBILE VARCHAR2(12),
	CONSTRAINT NEW_DONEE_PK PRIMARY KEY (ID)
);

DROP SEQUENCE DONEE_SEQUENCE;
CREATE SEQUENCE DONEE_SEQUENCE;

CREATE OR REPLACE TRIGGER NEW_DONEE_ON_INSERT
BEFORE INSERT ON NEW_DONEE
FOR EACH ROW
BEGIN
SELECT DONEE_SEQUENCE.NEXTVAL
INTO :NEW.ID
FROM DUAL;
END;
/

